workflows:
    simulator-native-ios:
        name: KeePassium
        max_build_duration: 120
        instance_type: mac_mini
        environment:
            vars:
               XCODE_WORKSPACE: "KeePassium.xcworkspace" # <-- Put the name of your Xcode workspace here
               XCODE_SCHEME: "your_workspace_name" # <-- Put the name of your Xcode scheme here
            xcode: 13.0

        scripts:

            - name: Build ipa for distribution
              script: |
                                xcode-project build-ipa --workspace "KeePassium.xcworkspace" --scheme "MyScheme"
        artifacts:
            - /tmp/xcodebuild_logs/*.log
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
