workflows:
    simulator-native-ios:
        name: KeePassium
        max_build_duration: 120
        instance_type: mac_mini
        environment:
            vars:
               XCODE_WORKSPACE: "KeePassium.xcworkspace" # <-- Put the name of your Xcode workspace here
              
            xcode: 13.0

        scripts:

            - name: Build ipa for distribution
              script: |
                                xcodebuild build -workspace "KeePassium.xcworkspace" CODE_SIGN_INDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        artifacts:
            - /tmp/xcodebuild_logs/*.log
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
